title: LG's Homepage
page-top-title: 李冠
top-section-bg-text: 我想要太多太多 灿如朝日，光芒透进 方寸鱼池，追光而去 上浮便知 幸福遍布人世。
home-subtitle: LG&ensp;|&ensp;bigcham-锦依卫
copyright-text: '&copy; LG 2023-2025. All Rights Reserved.'
